### ISSUE TITLE
RuntimeError: Cannot reopen a client instance, once it has been closed.

### ISSUE THREAD

**Issue by mdale100** [jacokok/warzone#5]
Thanks for your work on this integration! 

When trying to add the integration, I'm getting the following error. I'm running 2021.9.7 with 1.0.4 of this integration

`2021-09-27 19:03:32 ERROR (MainThread) [custom_components.warzone.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/warzone/config_flow.py", line 76, in async_step_user
    info = await validate_input(self.hass, user_input)
  File "/config/custom_components/warzone/config_flow.py", line 50, in validate_input
    if not await wz.authenticate():
  File "/config/custom_components/warzone/config_flow.py", line 39, in authenticate
    client = await Login(self.username, self.password)
  File "/config/custom_components/warzone/lib/auth.py", line 133, in Login
    await auth.SubmitLogin()
  File "/config/custom_components/warzone/lib/auth.py", line 103, in SubmitLogin
    async with self.session as client:
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1955, in __aenter__
    raise RuntimeError(msg)
RuntimeError: Cannot reopen a client instance, once it has been closed.`

**Comment by jacokok** [comment]
Can confirm this is an issue. The older cod library is likely not working anymore. Will update and check soon.

**Comment by jacokok** [comment]
Seems like they changed api again.

From package I am using.

Authorization using an email and password is not publicly available at this time. The aforementioned SSO method is to be used until further notice.

https://github.com/EthanC/CallofDuty.py/releases/tag/1.3.0

Might have to add SSO option until email password works again.

**Comment by jacokok** [comment]
https://github.com/EthanC/CallofDuty.py/issues/68
